swagger: "2.0"
info: 
  version: "0.0.1"
  title: "cpuinfo"
  description: "A simple service to get cpuinfo as an example of using swagger-2.0 specification and codegen"
  termsOfService: "http://swagger.io/terms/"
  contact: 
    name: "Cloudmesh REST Service Example"
  license: 
    name: "Apache"
host: "localhost:8080"
basePath: "/cloudmesh/nfl-analysis/v1"
schemes: 
  - "http"
consumes: 
  - "application/json"
produces: 
  - "application/json"
paths: 
  /results:
    get:
      tags:
        - NFL-ANALYSIS
      operationId: nfl-analysis.hello
      description: "Returns cpu information of the hosting server"
      produces: 
        - "application/json"
      responses: 
        "200":
          description: "NFL FF Prediction"
          schema: 
            $ref: "#/definitions/NFL-ANALYSIS"
definitions:
  NFL-ANALYSIS:
    type: "object"
    properties: 
      model:
        type: "string"

